import type { Metadata } from "next";
import { Inter, Content } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar/Navbar";
import Modal from "./components/modals/Modal";
import LoginModal from "./components/modals/LoginModal";

const inter = Inter({
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Django airbnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content =(
    <p>yo yo yo</p>
  )
  return (
    <html lang="en">
      <body
        className={inter.className}>
        <NavBar/>
        <div className="pt-28">
        {children}
        </div>
        <LoginModal/>
      </body>
    </html>
  );
}
